### ISSUE TITLE
Add support for Account Memberships endpoint

### ISSUE THREAD

**Issue by himanshu-garg-165** [salsita/go-pivotaltracker#13]
Hi, Thanks for the library!! :smiley:

However, there is no support for [Account Memberships](https://www.pivotaltracker.com/help/api/rest/v5#Account_Memberships) API in the library as of now, it would be better if we also have that service developed.

Nevertheless, I am really in need of that service, so I am developing that part of the library under our forked version [https://github.com/iReflect/go-pivotaltracker](https://github.com/iReflect/go-pivotaltracker).

Please let me know if you have anything in your plans for the same.

P.S: I'll create a pull request for the same once its development is complete.

Thanks !!!

**Comment by tchap** [comment]
Hi,

I don't think anybody is working actively on this right now. I will try to merge any pull request ASAP in case you decide to send it upstream ;-)

Cheers!

**Comment by tchap** [comment]
This is closed by #14 I guess.
